name: "Setup Flutter"
description: "Setup Flutter with dependencies"
runs:
  using: "composite"
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
    - name: Install dependencies
      run: flutter pub get
      shell: bash
